/*************************************************************************************************
* CS 562 Project
* Author: Yujie Du(10372723), Chuanhui Zhang(10387654)
*
* This class is generated by MFStructGenerator.java, generated at 2014-05-10 03:01:42
* It is required by MFMain class.
*
*************************************************************************************************/

package imagineDragon;

public class MFStruct { 
	 private String prod;
	 private String cust;
	 private int avg_2_quant;
	 private int sum_2_quant;
	 private int sum_0_quant;
	 private int count_3_state;
	 private int avg_0_quant;
	 private int count_0_quant;
	 private String min_1_state;
	 private int count_2_quant;
	 private int sum_1_quant;
	 private String max_1_state;

	 public MFStruct(String prod, String cust) {
		this.prod = prod;
		this.cust = cust;
		this.avg_2_quant = Integer.MIN_VALUE;
		this.sum_2_quant = Integer.MIN_VALUE;
		this.sum_0_quant = Integer.MIN_VALUE;
		this.count_3_state = Integer.MIN_VALUE;
		this.avg_0_quant = Integer.MIN_VALUE;
		this.count_0_quant = Integer.MIN_VALUE;
		this.min_1_state = "";
		this.count_2_quant = Integer.MIN_VALUE;
		this.sum_1_quant = Integer.MIN_VALUE;
		this.max_1_state = "";
	}

	 public String get_prod () {
		 return prod;
	}

	 public String get_cust () {
		 return cust;
	}

	 public int get_avg_2_quant () {
		if(this.count_2_quant != Integer.MIN_VALUE) avg_2_quant = sum_2_quant/count_2_quant;
		 return avg_2_quant;
	}

	 public void set_avg_2_quant (int value ) {
		 this.avg_2_quant = value;
	}

	 public int get_sum_2_quant () {
		 return sum_2_quant;
	}

	 public void set_sum_2_quant (int value ) {
		if(this.sum_2_quant == Integer.MIN_VALUE) this.sum_2_quant = value;
		 else this.sum_2_quant += value;
	}

	 public int get_sum_0_quant () {
		 return sum_0_quant;
	}

	 public void set_sum_0_quant (int value ) {
		if(this.sum_0_quant == Integer.MIN_VALUE) this.sum_0_quant = value;
		 else this.sum_0_quant += value;
	}

	 public int get_count_3_state () {
		 return count_3_state;
	}

	 public void set_count_3_state (Object value ) {
		if(this.count_3_state == Integer.MIN_VALUE) this.count_3_state = 1;
		else this.count_3_state ++;
	}

	 public int get_avg_0_quant () {
		if(this.count_0_quant != Integer.MIN_VALUE) avg_0_quant = sum_0_quant/count_0_quant;
		 return avg_0_quant;
	}

	 public void set_avg_0_quant (int value ) {
		 this.avg_0_quant = value;
	}

	 public int get_count_0_quant () {
		 return count_0_quant;
	}

	 public void set_count_0_quant (Object value ) {
		if(this.count_0_quant == Integer.MIN_VALUE) this.count_0_quant = 1;
		else this.count_0_quant ++;
	}

	 public String get_min_1_state () {
		 return min_1_state;
	}

	 public void set_min_1_state (String value ) {
		if(this.min_1_state.compareTo(value) > 0 || this.min_1_state.equals("")) this.min_1_state = value;
	}

	 public int get_count_2_quant () {
		 return count_2_quant;
	}

	 public void set_count_2_quant (Object value ) {
		if(this.count_2_quant == Integer.MIN_VALUE) this.count_2_quant = 1;
		else this.count_2_quant ++;
	}

	 public int get_sum_1_quant () {
		 return sum_1_quant;
	}

	 public void set_sum_1_quant (int value ) {
		if(this.sum_1_quant == Integer.MIN_VALUE) this.sum_1_quant = value;
		 else this.sum_1_quant += value;
	}

	 public String get_max_1_state () {
		 return max_1_state;
	}

	 public void set_max_1_state (String value ) {
		if(this.max_1_state.compareTo(value) < 0 || this.max_1_state.equals("")) this.max_1_state = value;
	}

}